myapp/urls.py
from django.conf.urls import url
from myapp import views
app_name ='quiz'
urlpatterns = [
    url('question/',views.quiz, name='question'),
    #url('result/',views.result, name='result'),
    url('facts/',views.facts, name='facts'),
    url('insertdata/',views.insertdata, name='insertdata'),
    url('about/',views.about, name='aboutdev'),
    url('board/',views.board, name='aboutdev'),

]

onlinequiz/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index' ),
    path('quiz/',include('myapp.urls'))
]

myapp/models.py
from django.db import models

class addQuestion(models.Model):
    CHOICES = (
    ('a','A'),
    ('b','B'),
    ('c','C'),
    ('d','D')
    )

    question = models.CharField(max_length=500)
    option1 = models.CharField(max_length = 250)
    option2 = models.CharField(max_length = 250)
    option3 = models.CharField(max_length = 250)
    option4 = models.CharField(max_length = 250)
    answer = models.CharField(max_length= 1, choices = CHOICES, blank=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, blank = True)

    def __str__(self):
        return self.question

# Create your models here.
class feedback(models.Model):
    name= models.CharField(max_length=200)
    email= models.EmailField(max_length=250)
    message = models.TextField()
    Date = models.DateTimeField(auto_now_add=True, blank = True)


    def __str__(self):
        return self.message

    class Meta:
        verbose_name_plural = 'Feedback'

class scoreboard(models.Model):
    Name = models.CharField(max_length=200, blank=True)
    Right_Answers= models.CharField(max_length=200)
    Wrong_Answers= models.CharField(max_length=250)
    Date = models.DateTimeField(auto_now_add=True, blank = True)

    def __str__(self):
        return repr(self.Date)

    class Meta:
        verbose_name_plural = 'Score Board'

class add_fact(models.Model):
    fact = models.TextField()
    author_name = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add= True, blank = True)

    def __str__(self):
        return self.fact

myapp/views.py
from django.shortcuts import render
from myapp.models import feedback, scoreboard, addQuestion, add_fact
from django.http import HttpResponse, HttpResponseRedirect
import requests
# Create your views here.
def index(request):
    if request.method =='POST':
        name = request.POST['name']
        email=request.POST['email']
        message=request.POST['message']
        feedbackobj = feedback(name=name,email=email,message=message)
        feedbackobj.save()
        print('data saved')

    return render(request, 'index.html')

def quiz(request):
    data = addQuestion.objects.order_by('created_at')
    right = 0
    wrong = 0
    data1 = []
    result = {}
    if request.method == 'POST':
        print(request.POST)
        for m in data:
            if request.POST['q'+repr(m.id)] == request.POST['answer'+repr(m.id)]:
                rr = {'status':'green','id':m.id,'question':m.question,'option1':m.option1,'option2':m.option2,'option3':m.option3,'option4':m.option4,'answer':m.answer,'useranswer':request.POST['q'+repr(m.id)],'description':m.description}
                data1.append(rr)
                right += 1
            else:
                rr = {'status':'red','id':m.id,'question':m.question,'option1':m.option1,'option2':m.option2,'option3':m.option3,'option4':m.option4,'answer':m.answer,'useranswer':request.POST['q'+repr(m.id)],'description':m.description}
                data1.append(rr)
                wrong += 1
        #print(data1)
        result['right'] = right;
        result['wrong'] = wrong;

        board = scoreboard.objects.order_by('Date')
        return render(request,'result.html',{'d':data,'d1':data1,'quiz':result,'board':board})


    return render(request,'quiz.html',{'d':data})
    # api = requests.get('http://sachtechsolution.com/dailydose/admin/webservice/questionsProcess.php?type=questions')
    # mydata= api.json()
    # right = 0
    # wrong = 0
    # result = {'myans':'active'}
    # count = 1
    # mynewdata = []
    # for q in mydata['Questions']:
    #
    #     dic = {'id':count,'question':q['question'],'qid':q['ques_id'],'a':q['option1'],'b':q['option2'],'c':q['option3'],'d':q['option4']}
    #     mynewdata.append(dic)
    #     count += 1
    # #print(mynewdata)
    # for a in mydata['Questions']:
    #     if request.method == 'POST' and request.POST:
    #         if a['answer'] == request.POST[a['ques_id']]:
    #             right += 1
    #         else:
    #             wrong += 1
    #
    #
    # result['right'] = right;
    # result['wrong'] = wrong;
    # print(result)
    # if result['right'] == 0 or result['wrong'] == 0:
    #     return render(request, 'quiz.html',context = {'quiz':mynewdata})
    # else:
    #     scores = scoreboard(Right_Answers=right, Wrong_Answers=wrong)
    #     scores.save()
    #     print('saved successfully')
    #     board = scoreboard.objects.order_by('Date')
    #
    #     return render(request, 'result.html',context = {'quiz':result,'des':mydata,'board':board})

def facts(request):
    data = add_fact.objects.order_by('date')
    return render(request, 'fact.html',{'facts':data})

#     apfact = requests.get('http://sachtechsolution.com/dailydose/admin/webservice/factProcess.php?type=getLanguageFacts&languageId=3')
#     data =apfact.json()
#     count = 1
#     mynewfact = []
#     for r in data['facts']:
#
#         dicfact = {'id':count,'thought':r['thought']}
#         mynewfact.append(dicfact)
#         count += 1
#     #print(mynewfact)
#     return render(request,'fact.html',context = {'fact':mynewfact})
def insertdata(request):
    if request.method == 'POST' and request.POST:
        m = request.POST['name']
        n = request.POST['right']
        o = request.POST['wrong']
        return HttpResponse(request.POST['name'])
    else:
        return HttpResponse('index hello')

def about(request):
    return render(request,'about.html')

def board(request):
    if request.method == 'POST':
        name = request.POST['nm']
        rt = request.POST['r']
        wr = request.POST['w']

        scores = scoreboard(Name= name, Right_Answers=rt, Wrong_Answers=wr)
        scores.save()
        print("Saved!!!")
    board = scoreboard.objects.order_by('Date')
    return render(request,'board.html',{'board':board})

templates/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>Online Quiz</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}" >
  </head>
  <body>
    <div class="row">
        <div class="col-md-12">
          <div class="carousel slide" id ='myid' data-ride='carousel'>
      <ul class="carousel-indicators">
        <li class="active"></li>
        <li></li>
        <li></li>
        <li></li>
      </ul>

      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="vee.jpg" alt="img1" height='600' width='100%'/>
        </div>


         <div class="carousel-item">
          <img src="rvee.jpg" alt="img3" height='600' width='100%'/>
        </div>

        <div class="carousel-item">
          <img src="hut1.jpg" alt="img1" height='600' width='100%'/>
        </div>

        <div class="carousel-item">
          <img src="hut2.jpg" alt="img1" height='600' width='100%'/>
        </div>


        <a class="carousel-control-prev" href="#myid" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a href="#myid" class='carousel-control-next' data-slide='next'>
          <i class="fas fa-forward"></i>
        </a>

        </div>

      </div>
    </div>
    </body>
</html>

templates/board.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <title>ONLINE QUIZ</title>
    <script src="{% static "js/jquery.js" %}"></script>
    <!-- Styles -->
    <link rel='stylesheet' href="{% static "css/bootstrap.min.css" %}">
    <link rel='stylesheet' href="{% static "css/animate.min.css" %}">
    <link rel='stylesheet' href="{% static "css/font-awesome.min.css" %}">
    <link rel='stylesheet' href="{% static "css/style.css" %}"/>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Online Quiz</title>
    <link rel="stylesheet" href="{% static "style.css" %}">
    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous"> -->
    <!-- Google Fonts -->
    <!-- <link href='https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700' rel='stylesheet' type='text/css'> -->
    <!-- Font Awesome -->
    <!-- <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel='stylesheet' type='text/css'> -->
    <!-- Style -->
    <link href='{% static 'style.css'%}' rel='stylesheet' type='text/css'>
    <script src='{% static 'fa5/js/all.min.js'%}'></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </script>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" style='font-family:arial;'><i class="fas fa-question mr-2" style='color:red; margin-right:10px;'></i>Online <span style='font-size:50px; color:red; font-family:arial;'>Q</span>uiz</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="http://127.0.0.1:8000/#quiz">Home</a></li>
            <li><a href="{% url "quiz:aboutdev"%}">Scoreboard</a></li>
            <li> <a href="http://127.0.0.1:8000/#about">About Us</a> </li>
            <li><a href="http://127.0.0.1:8000/#slider">Testimonials</a></li>
            <li><a href="http://127.0.0.1:8000/#gallery">Our Experts</a></li>
            <li> <a href="http://127.0.0.1:8000/#contact">Contact Us</a> </li>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-center">Scoreboard</h1>
          <table class='table my-5 table-hover'>
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Correct Answers</th>
                <th>Wrong Answers</th>
                <th>Date</th>
              </tr>
            </thead>
            {% for i in board %}
            <tbody>
              <tr>
                <td> {{i.id}} </td>
                <td> {{i.Name}} </td>
                <td>{{ i.Right_Answers }}</td>
                <td>{{ i.Wrong_Answers }}</td>
                <td> {{ i.Date }} </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
        <!-- <div class="col-md-4 mx-auto my-5 ">
          <form class=""  method="post">
            {% csrf_token%}
            <div class="form-group">
              <input type="text" name="nm" value="" placeholder='Enter Name...' id='name' class='form-control'>
            </div>
            <div class="form-group">
              <input type="number" name="r" value="" placeholder='Right Answers' id='right' class='form-control'>
            </div>
            <div class="form-group">
              <input type="number" name="w" value="" placeholder='wrong answers' id='wrong' class='form-control'>
            </div>
            <div class="form-group">
              <input type="submit"  value="Submit" placeholder='Enter Name...' class='btn btn-info btn-block'>
            </div>
          </form>
        </div> -->
      </div>
    </div>
  </body>
</html>

templates/fact.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>ONLINE QUIZ</title>
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}">
    <script src='{% static 'fa5/js/all.min.js'%}'></script>

    <style>
    .transbox {
       margin:5%;
       padding:5%;
       background-color: #ffffff;
       border: 2px solid red;
       opacity: 0.6;
       border-radius: 10px;
 }
 .sq:hover{
   color:black;
 }
    </style>
  </head>
  <body class=""  style='background:rgba(255,0,0,0.2)'>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 px-0">
          <nav class='navbar bg-dark navbar-dark navbar-expand-sm'>
            <a href="{% url "index"%}" class='navbar-brand'>Online Quiz</a>
            <ul class='navbar-nav ml-auto'>
              <a href="{% url "quiz:question"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> <<< Start Quiz!!!</li>
              </a>
              <a href="{% url "index"%}" class='nav-link btn btn-outline-light'>
                <li class='nav-item sq'> Go to Homepage</li>
              </a>
            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row" style="background:url('{% static 'images/mystery.jpg'%}');padding:7%;background-size: 100% 100%;  background-attachment:fixed;">
        <div class="col-md-6 mx-auto">
          <h1 class='transbox mx-auto'><i class="fas fa-question mr-2" style='color:red; margin-right:10px;'></i> Did you Know <i class="fas fa-question mr-2" style='color:red; margin-right:10px;'></i><i class="fas fa-question mr-2" style='color:red; margin-right:10px;'></i></h1>

        </div>
      </div>
    </div>
    <div class="container">
      <div class=" col-md-12 bg-light p-5 m-5">
          <table class="table table-striped alert alert-s ">
            <tbody>
          {% for i in facts %}
              <tr>
                <td><strong>{{i.id}} . </strong> {{i.fact}} </td>
              </tr>

          {% endfor %}
          </tbody>
          </table>
      </div>
    </div>
    <div class="container-fluid text-center" style='margin:0px;' id='about'>
      <div class="row">
        <div class="col-md-12" style="padding:3%; background:black; color:white;">
          <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Ritika Sharma <br/>
          <span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

        </div>
      </div>
    </div>
  </body>
</html>

templates/quiz.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}" >
    <script src="{% static "js/jquery.js" %}"></script>
    <script src='{% static 'fa5/js/all.min.js'%}'></script>
    <title>QUIZ</title>
    <style>
    div.transbox {
       margin:5%;
       background-color: rgba(255,255,255,.9);
       border: 1px solid red;
       padding:2%;
       border-radius: 10px;
 }
.sq:hover{
  color:black;
}
  </style>
  </head>
  <body style='background:rgba(250,0,0,0.1)'>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 px-0">
          <nav class='navbar bg-dark navbar-dark navbar-expand-sm'>
            <a href="{% url "index"%}" class='navbar-brand'>Online Quiz</a>
            <ul class='navbar-nav ml-auto'>
              <li class="nav-item">
                <a href="{% url "index"%}" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                <a href="#quiz" class="nav-link">Start Quiz <i class="fas fa-arrow-down ml-2"></i></a>
              </li>

              <!-- <a href="" class='nav-link btn btn-outline-light'>
                <li class='nav-item sq'>Start quiz</li>
              </a> -->
              <!-- <a href="{% url "index"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> <<< Home</li>
              </a> -->

            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="container-fluid ">
      <div class="row h-100 justify-content-center py-4" style="font-family:arial;  background-image: url('{% static 'images/quiz.jpeg' %}'); background-size:100% 100%; background-attachment:fixed;">
        <div class="col-md-6 transbox">
          <h2 class=' text-dark text-center'>Are you here</h2><h2 class='pl-5 text-success' style='margin-left:20%;'> with the SOLUTION</h2>
          <h1 class='text-center'>or Are you Part of the<br/> <span  style='font-weight:bold; color:red;'>Problem ???<i class="fas fa-question" style='font-size:50px;'></i></span></h1>
        </div>
      </div>
      <div class="row " id='quiz'>
        <div class="col-md-9 bg-light my-5 py-5" style='margin:0 auto; border:1px solid red; border-radius:10px; '>
          <form method="post" action="">

            {% csrf_token %}
            {% for i in d %}
              <div type='1' class='alert alert-danger mt-5'><strong>{{i.id}} . </strong>{{ i.question }}</div>

                <div class='aabb form-control'><input type="radio" value='a' name='q{{ i.id }}' checked />{{ i.option1}}</div>
                <div class='aabb form-control'><input type="radio" value='b' name='q{{ i.id }}' />{{ i.option2 }}</div>
                <div class='aabb form-control'><input type="radio" value='c' name='q{{ i.id }}' />{{ i.option3 }}</div>
                <div class='aabb form-control'><input type="radio" value='d' name='q{{ i.id }}' />{{ i.option4 }}</div>
                <input type="hidden" name="answer{{i.id}}" value="{{i.answer}}" />
              {% endfor %}
              <br/>
              <input type="submit" class='btn btn-block btn-success py-2 my-4' />
              </div>

          </form>
        </div>
      </div>
    </div>
    <script>
      $(document).ready(function(){
        $('.aabb').click(function(){
          $(this).css("color","orange");
        });
      });
    </script>
    <div class="container-fluid text-center" style='margin:0px;' id='about'>
      <div class="row">
        <div class="col-md-12" style="padding:3%; background:black; color:white;">
          <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Ritika Sharma <br/>
          <span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

        </div>
      </div>
    </div>

  </body>
</html>

templates/result.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>ONLINE QUIZ</title>
    <script src="{% static "js/jquery.js" %}"></script>

    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}" />
    <script src='{% static 'fa5/js/all.min.js'%}'></script>

    <script>
      $(document).ready(function(){
        //document.getElementById('name1').innerHTML = '<i class="fas fa-user mr-2"></i>';
        var x = prompt('Very nice attempt, Please tell me your Name!!!');
        $('#name112').html(" " + x);
        $('#n2').html(" " + x);
        var token1 = $("input[name='csrfmiddlewaretoken']").val();
        //alert(token1);
        var right = '{{ quiz.right }}';
        var wrong = '{{ quiz.wrong }}';

        if(x=='' || x==null){
          document.write('<h1> Name required!!!</h1>');
        }
        else{

          $.ajax({
             method: "POST",
             url: "http://127.0.0.1:8000/quiz/board/",
             data: { nm: x, r:right, w:wrong,csrfmiddlewaretoken:token1 },
             success: function(data){
               //alert('data');
             }
           });
        }
      });

    </script>
    <script>
      $(document).ready(function(){
        $('#button').click(function(){
          $('#scoreb').fadeToggle(2000);
        });
      });
    </script>

    <style>
.sq:hover{
  color:black;
}
  </style>
  </head>
  <body>
    {% csrf_token %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12 px-0">
          <nav class='navbar bg-dark navbar-dark navbar-expand-sm'>
            <a href="{% url "index"%}" class='navbar-brand'>Online Quiz</a>
            <ul class='navbar-nav ml-auto'>
              <a href="{% url "quiz:question"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> << Start Again!!!</li>
              </a>
              <a href="{% url "index"%}" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq '> <<< Home</li>
              </a>
              <a href="#details" class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq'> View Answer Description</li>
              </a>
              <a href="#scoreb" id='button' class='nav-link btn btn-outline-light mr-2'>
                <li class='nav-item sq'> View Previous scoreboard</li>
              </a>
              <a href="#" class='nav-link'>
                <li class='nav-item' ><span id='name112' name='res' class='nav-item'> </span></li>
                <!-- <form class="" name='myform' method="post">
                  {% csrf_token %}
                  {{ myform.as_p }}
                  <input type="text" id='na' name=

                  'na' value=""/>
                </form> -->

              </a>

            </ul>
          </nav>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row" style='background:rgba(255,0,0,0.1); background-attachment:fixed;'>
        <div class="container">
          <div class="row my-5">
            <div class="col-md-12">
              <h1 class="text-center alert-success my-5 pb-5" id='name' style='box-shadow:20px 10px 10px red;'>Hello<span id='n2'></span> here is your result</h1>
            </div>
            <div class="col-md-6 mx-auto mt-5 p-2 bg-light">
              <div class="bg-success py-5">
                <h1 class="text-center display-1">{{ quiz.right }}</h1>
              </div>
            </div>
            <div class='col-md-6 mx-auto mt-5 p-2 bg-light'>
              <div class="bg-danger py-5">
                <h1 class="text-center display-1">{{ quiz.wrong }}</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid p-5 " id='details' style='background:rgba(0, 255, 0,0.1); background-attachment:fixed; '>
      <div class="row">
        <div class="col-md-9 mx-auto bg-light p-5" style='border-radius:20px;'>
          <h1 class='text-warning text-center p-5 mb-5' style='background:rgba(125,50,125,0.1);  '>Here is Details of Answer</h1>

            {% for j in d1%}
              <dl class="list-group my-3 bg-dark p-5">

              <dd class='alert alert-light p-2 ' style='font-size:20px;color:{{j.status}};'><strong>Question:</strong>{{ j.question }}</dd>
              <dd class='alert alert-dark' style="color:{{j.status}};">a. {{ j.option1 }}</dd>
              <dd class='alert alert-dark' style="color:{{j.status}};">b. {{ j.option2 }}</dd>
              <dd class='alert alert-dark' style="color:{{j.status}};">c .{{ j.option3 }}</dd>
              <dd class='alert alert-dark' style="color:{{j.status}};">d .{{ j.option4 }}</dd>
              <dd class='alert alert-info' style="color:{{j.status}};"><strong>Your answer is : </strong>{{ j.useranswer }}</dd>
              <dd class='alert alert-info p-3' style="color:{{j.status}};"><strong>Description:</strong>{{ j.description }}</dd>
              <dd class='alert alert-info p-3' style="color:{{j.status}};"><strong>Correct Option:</strong> {{ j.answer }}</dd>
              </dl>
            {% endfor %}

            {% for i in d %}


              <!-- <dd class='alert alert-info p-2 ' style='font-size:20px'><strong>Question:</strong>{{ i.question }}</dd>
              <dd class='alert alert-dark'>a. {{ i.option1 }}</dd>
              <dd class='alert alert-dark'>b. {{ i.option2 }}</dd>
              <dd class='alert alert-dark'>c .{{ i.option3 }}</dd>
              <dd class='alert alert-dark'>d .{{ i.option4 }}</dd>
              <dd class='alert alert-success p-3'><strong>Description:</strong>{{ i.description }}</dd>
              <dd class='alert alert-success p-3'><strong>Correct Option:</strong> {{ i.answer }}</dd> -->
            {% endfor %}


        </div>
      </div>
    </div>
    {% if board %}
    <div class="container-fluid my-5" id='scoreb' style='display:none; border-radius:10px;'>
      <div class="row">
        <div class="col-md-12">
          <h1 class='py-5 my-3 text-center text-success'style='background:rgba(255,0,0,0.1)'>Here is previous Score Board</h1>
        </div>
        <div class="col-md-12">
          <table class='table my-5 table-hover'>
            <thead>
              <tr>
                <th>Sr. No</th>
                <th>Name</th>
                <th>Correct Answers</th>
                <th>Wrong Answers</th>
                <th>Date</th>
              </tr>
            </thead>
            {% for i in board %}
            <tbody>
              <tr>
                <td> {{i.id}} </td>
                <td> {{i.Name}} </td>
                <td>{{ i.Right_Answers }}</td>
                <td>{{ i.Wrong_Answers }}</td>
                <td> {{ i.Date }} </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
    {% endif %}
    <div class="container-fluid text-center" style='margin:0px;' id='about'>
      <div class="row">
        <div class="col-md-12" style="padding:3%; background:black; color:white;">
          <strong>Powered By :</strong> <br/> <i class="fa fa-user" style='padding-right:2px;'></i> Ritika Sharma <br/>
          <span class='justify-content-center'>Copyright &copy; <a href="http://www.sachtechsolution.com/" style='color:white;'>Sachtech Solution Pvt. ltd.</a></span>

        </div>
      </div>
    </div>

  </body>
  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"> -->
</html>